spring.application.name=shop

# Supabase Connection Parameters — loaded from environment variables
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?user=postgres.rxdpfzkgyhhjgbkdwvtb&password=[password]
spring.datasource.username=postgres.[username]
spring.datasource.password=[PASSWORD]
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect